services:
  - type: web
    name: lead-distribution-platform-v2
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run deploy
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lead-platform-db-v2
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /

databases:
  - name: lead-platform-db-v2
    databaseName: lead_distribution_v2
    user: lead_admin